### ISSUE TITLE
DAPAR workflow

### ISSUE THREAD

**Issue by annajbott** [samWieczorek/DAPAR#6]
Hi,
I was wondering if you have a workflow for using DAPAR as a standalone R package, without using Prostar?

Thanks,
Anna

**Comment by samWieczorek** [comment]
Hi Anna,

In a classical way, the functions in DAPAR are accessed by the UI provided by the package Prostar. However, DAPAR’s functions are directly available in a R console. We do not provide any workflow for DAPAR only as the workflows are implemented in Prostar. So, you have to write your own workflows in a script. For that, you can take ideas with the example provided for each function in DAPAR. May I ask you the reason why you do not want to use Prostar ?

PS : In order to have a quicker answer, it is better to send your questions/remarks at the author’s email  : thomas.burger@cea.fr<mailto:thomas.burger@cea.fr>, samuel.wieczorek@cea.fr

Best regards

Sam


De : Anna James-Bott <notifications@github.com>
Envoyé : mardi 7 janvier 2020 16:03
À : samWieczorek/DAPAR <DAPAR@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [samWieczorek/DAPAR] DAPAR workflow (#6)


Hi,
I was wondering if you have a workflow for using DAPAR as a standalone R package, without using Prostar?

Thanks,
Anna

**Comment by annajbott** [comment]
Hi Sam,
Thank you for your reply. I have not analysed protein data before so I'm trying to learn as I go along
I work on a cluster on a virtual desktop so it can be quite clunky and I have no sudo rights. I have tried the ProStar UI, but I can't seem to load and convert my proteomics data (I don't have the raw data only log-transformed data in a CSV file) . Additionally, I have both proteomics and phosphoproteomics data and was hoping to compare it to some transcriptomics data, so I thought using R would be easier.  
I have only just seen the command line prompts alongside the Prostar instructions. I will work through my data using these. Thanks a lot, I'll comment again/email if I have any problems!

Thanks,
Anna
